config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  get 'chat' => 'chat#chat'
  get 'candy' => 'chat#candy'
  get 'converse' => 'chat#converse'
  get 'register' => 'chat#register'
  get 'reveal' => 'chat#reveal'
  get 'prebind' => 'chat#prebind'
  get 'links' => 'links#index'
  get 'background' => 'backgrounds#random'
  get 'dropbox' => 'backgrounds#dropbox'
  get 'ftp' => 'backgrounds#ftp'

  resources :backgrounds, only: [] do
    collection do
      get :gallery
    end
  end

  root 'chat#index'

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController

  before_filter :require_login, only: [:chat, :reveal, :candy]

  rescue_from Bosh::Error do |exception|
    flash[:alert] = exception.message
    redirect_to register_path
  end

  def index
    if user_signed_in?
      redirect_to chat_path
    else
      redirect_to register_path
    end
  end

  def chat
    @ajax_client_path =
      if params[:converse]
        converse_path
      else
        candy_path
      end
  end

  def converse
    render layout: "empty"
  end

  def reveal
    render layout: false
  end

  def candy
    # if current_user.id == 3
    #   if params[:bosh4r]
    #     instance = Bosh4r::Session.new(current_user.jid, current_user.xmpp_password, bosh_url: "https://#{XMPP_HOST}/http-bind/")
    #     @credentials = {
    #       sid: instance.sid,
    #       jid: instance.jabber_id,
    #       rid: instance.rid
    #     }
    #   else
    #     @credentials =
    #       Bosh.initialize_session current_user.jid, current_user.xmpp_password, "https://#{XMPP_HOST}/http-bind/"
    #   end

    #   render layout: "empty"
    # else
    #   render text: "<p><b>Currently broken. :(</b><br />Please use a chat client and the credentials available in the upper-right corner of the window.</p>".html_safe
    # end

    @credentials =
      Bosh.initialize_session current_user.jid, current_user.xmpp_password, "https://#{XMPP_HOST}/http-bind/"

    render layout: "empty"
  end

  def register
    #
  end

  def prebind
    credentials =
      Bosh.initialize_session current_user.jid, current_user.xmpp_password, "https://#{XMPP_HOST}/http-bind/"

    # render json: {
    #   jid: current_user[:jid],
    #   sid: credentials[:sid],
    #   rid: credentials[:rid]
    # }

    render json: credentials
  end

  private

  def default_chat_room
    case Rails.env
    when 'development' then 'main'
    when 'production' then 'chat'
    end
  end
  helper_method :default_chat_room

  def require_login
    unless user_signed_in?
      flash[:alert] = "You have to be signed in to see that"
      redirect_to register_path
    end
  end
end

app/helpers/chat_helper.rb
module ChatHelper
  def candy_bookmark_rooms
    bookmarks = []
    current_user.rooms.collect(&:jid).each do |jid|
      bookmarks << "CandyShop.Bookmark.add('#{jid}');"
    end
    bookmarks.join("\n")
  end

  def candy_autojoin_rooms
    current_user.rooms.collect(&:jid).to_json
  end

  def candy_room_panel_user_rooms
    current_user.rooms.collect do |room|
      { name: room.name, jid: room.jid }
    end.to_json
  end

  def reveal(field)
    content_tag(:code, "Click to reveal", class: "reveal-#{field}")
  end
end

app/views/chat/candy.html.haml
#candy

- content_for :stylesheets do
  %link( rel="stylesheet" type="text/css" href="/candy/res/default.css" )

  / %link( rel="stylesheet" type="text/css" href="/plugins/stickysubject/candy.css" )
  / %link( rel="stylesheet" type="text/css" href="/plugins/roomPanel/default.css" )
  %link( rel="stylesheet" type="text/css" href="/plugins/replies/candy.css" )
  %link( rel="stylesheet" type="text/css" href="/plugins/nickchange/candy.css" )
  %link( rel="stylesheet" type="text/css" href="/plugins/notifyme/candy.css" )
  %link( rel="stylesheet" type="text/css" href="/plugins/namecomplete/candy.css" )
  %link( rel="stylesheet" type="text/css" href="/plugins/mucroombar/mucroombar.css" )
  %link( rel="stylesheet" type="text/css" href="/plugins/inline-images/candy.css" )

  = stylesheet_link_tag "candy/textarea.css"

  = stylesheet_link_tag :candy

- content_for :javascript do
  %script( type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" )
  %script( type="text/javascript" src="/candy/libs/libs.min.js" )
  %script( type="text/javascript" src="/candy/candy.min.js" )

  / %script( type="text/javascript" src="/plugins/stickysubject/candy.js" )
  %script( type="text/javascript" src="/plugins/slash-commands/slash-commands.js" )
  / %script( type="text/javascript" src="/plugins/roomPanel/roomPanel.js" )
  %script( type="text/javascript" src="/plugins/replies/candy.js" )
  %script( type="text/javascript" src="/plugins/refocus/candy.js" )
  %script( type="text/javascript" src="/plugins/nickchange/candy.js" )
  %script( type="text/javascript" src="/plugins/notifyme/candy.js" )
  %script( type="text/javascript" src="/plugins/notifications/candy.js" )
  %script( type="text/javascript" src="/plugins/namecomplete/candy.js" )
  %script( type="text/javascript" src="/plugins/mucroombar/mucroombar.js" )
  / %script( type="text/javascript" src="/plugins/me-does/candy.js" )
  %script( type="text/javascript" src="/plugins/join/candy.js" )
  %script( type="text/javascript" src="/plugins/inline-videos/candy.js" )
  %script( type="text/javascript" src="/plugins/inline-images/candy.js" )
  / %script( type="text/javascript" src="/plugins/emphasis/candy.js" )
  / %script( type="text/javascript" src="/plugins/chatrecall/candy.js" )
  %script( type="text/javascript" src="/plugins/bookmark/bookmark.js" )

  = javascript_include_tag "candy/textarea.js"

  :javascript
    $(document).ready(function() {
      Candy.init('https://#{XMPP_HOST}/http-bind/', {
        core: {
          // only set this to true if developing / debugging errors
          // debug: true,
          // autojoin is a *required* parameter if you don't have a plugin (e.g. roomPanel) for it
          //   true
          //     -> fetch info from server (NOTE: does only work with openfire server)
          //   ['test@conference.example.com']
          //     -> array of rooms to join after connecting
          autojoin: #{candy_autojoin_rooms}
        },
        view: { assets: '/candy/res/' }
      });

      // Plugins!
      // CandyShop.StickySubject.init();
      CandyShop.SlashCommands.defaultConferenceDomain = '#{CONFERENCE_HOST}';
      CandyShop.SlashCommands.init();

      // Get rid of roompanel?
      // CandyShop.RoomPanel.init({
      //   mucDomain: '#{CONFERENCE_HOST}',
      //   roomList: #{candy_room_panel_user_rooms},
      //   showIfAllTabClosed: true,
      //   showTab: false,
      //   showToolbarIcon: false,
      //   autoDetectRooms: false,
      //   roomCacheTime: 600
      // });

      CandyShop.Replies.init();
      CandyShop.Refocus.init();
      CandyShop.Nickchange.init();
      // CandyShop.NotifyMe.init(); // Complains at getNick
      CandyShop.Notifications.init();
      CandyShop.NameComplete.init();
      CandyShop.RoomBar.init();
      // See https://groups.google.com/d/msg/candy-chat/G_URFxlpHfw/qPM5c8UYJZ0J
      // CandyShop.MeDoes.init();
      CandyShop.Join.init();
      CandyShop.InlineVideos.init(); // Make the videos appear larger
      CandyShop.InlineImages.init({ maxImageSize: 250, spinner: '/plugins/inline-images/spinner.gif' });
      // CandyShop.Emphasis.init(); // Doesn't do what you think it does.
      // CandyShop.ChatRecall.init();
      CandyShop.Bookmark.init();
      CandyShop.Textarea.init();

      // And we're done here
      Candy.Core.attach(
        '#{@credentials[:jid]}',
        '#{@credentials[:sid]}',
        #{@credentials[:rid]}
      );

      // How many unread messages do we have in total? There will be a way of
      // querying Candy directly but this works for now.
      function getUnreadMessageCount() {
        total = 0;
        $('#chat-tabs small.unread').each(function(n) {
          $element = $(this);
          if ($element.is(':visible')) {
            total += parseInt($element.text());
          }
        })
        return total;
      }

      // Update the top window title with the new message count.
      function updateUnreadMessageCount(count) {
        if (window.parent) {
          if (typeof count == 'undefined') {
            count = getUnreadMessageCount();
          }
          window.parent.updateUnreadMessageCount(count);
        }
      }

      window.updateUnreadMessageCount = updateUnreadMessageCount

      // Update when we focus or blur the window.
      $(window).focus(function() {
        updateUnreadMessageCount()
      }).blur(function() {
        updateUnreadMessageCount()
      });

      // Update when a new message is rendered.
      $(Candy).on('candy:view.message.after-show', function(event, data) {
        updateUnreadMessageCount();
      });

      // Update just after a tab is opened.
      $('#chat-tabs').click(function(event) {
        setTimeout(updateUnreadMessageCount, 50);
      });

      // Send the user to the login page if we've been logged out
      $(Candy).on('candy:core.login', function(event, data) {
        updateUnreadMessageCount(-1);
        top.location.replace('#{root_url}')
      });

      // Now bookmark the default rooms
      //
      // Just a stand-in until I figure out how to get xmpp4r to do it.
      #{candy_bookmark_rooms}
    });

app/views/chat/chat.html.haml
.row#candyContainer
  .col-md-12
    %iframe#candy( width="100%" height="100%" src="#{@ajax_client_path}" frameBorder="0" scrolling="no" allowTransparency="true" style="background-color: transparent;")

#connect.modal.fade(tabIndex="-1" role="dialog")
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close(type="button" data-dismiss="modal")
          %span &times;
        %h4.modal-title Integration
      .modal-body
        .row
          .col-md-6
            %p
              r/vanchat.com is a Jabber/XMPP server running Prosody. This means that
              you can connect any client that supports Multi-User-Chat (MUC).
          .col-md-6
            %p
              Here are some suggested clients by platform. I haven't been able to
              test all of these out personally so if you have better recommendations
              please let me know.

        %div
          %ul.nav.nav-tabs
            %li
              = link_to "#credentials", data: { toggle: 'tab' } do
                Credentials

            %li.active
              = link_to "#android", data: { toggle: 'tab' } do
                %i.fa.fa-android
                Android

            %li
              = link_to "#osx", data: { toggle: 'tab' } do
                %i.fa.fa-apple
                OS X

            %li
              = link_to "#ios", data: { toggle: 'tab' } do
                %i.fa.fa-apple
                iPhone / iPad

            %li
              = link_to "#windows", data: { toggle: 'tab' } do
                %i.fa.fa-windows
                Windows

            %li
              = link_to "#linux", data: { toggle: 'tab' } do
                %i.fa.fa-linux
                Linux

          .tab-content
            #credentials.tab-pane
              #reveal
                %h4= link_to "Reveal credentials", reveal_url

            #android.tab-pane.active
              %h4
                = link_to "https://play.google.com/store/apps/details?id=eu.siacs.conversations", target: "_blank" do
                  Conversations
                  %small $2.99
                %small
                  = link_to "Instructions", "#instructions-android-conversations", data: { toggle: "collapse" }

              #instructions-android-conversations.collapse
                .well.well-sm= render 'instructions/conversations'

              %h4
                = link_to "https://play.google.com/store/apps/details?id=com.xabber.android", target: "_blank" do
                  Xabber
                  %small Free / $3.00

            #osx.tab-pane
              %h4
                = link_to "https://adium.im/", target: "_blank" do
                  Adium
                  %small Free
                %small
                  = link_to "Instructions", "#instructions-osx-adium", data: { toggle: "collapse" }

              #instructions-osx-adium.collapse
                .well.well-sm= render 'instructions/adium'

              %h4
                = link_to "http://monal.im/", target: "_blank" do
                  Monal (beta)
                  %small Free

            #ios.tab-pane
              %h4
                = link_to "https://itunes.apple.com/ca/app/monal-free-xmpp-chat/id317711500?mt=8", target: "_blank" do
                  Monal
                  %small Free

            #windows.tab-pane
              %h4
                = link_to "http://pidgin.im/", target: "_blank" do
                  Pidgin
                  %small Free
              %h4
                = link_to "http://www.gajim.org/", target: "_blank" do
                  Gajim
                  %small Free

            #linux.tab-pane
              %h4
                = link_to "http://pidgin.im/", target: "_blank" do
                  Pidgin
                  %small Free
              %h4
                = link_to "http://www.gajim.org/", target: "_blank" do
                  Gajim
                  %small Free

- content_for :header_right do
  = link_to "#", class: "btn btn-default btn-lg btn-primary", data: { toggle: "modal", target: "#connect" } do
    %i.fa.fa-android
    %i.fa.fa-apple
    %i.fa.fa-windows
  = link_to "#", class: "btn btn-default btn-lg btn-primary", id: "swap-background" do
    %i.fa.fa-image

- content_for :javascript do
  :javascript
    $(startBackgrounds);

app/views/chat/converse.html.haml
- content_for :stylesheets do
  %meta(charset="utf-8")
  %meta(meta http-equiv="Content-Type" content="text/html; charset=utf-8")
  %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  = stylesheet_link_tag "//cdn.jsdelivr.net/bootstrap/3.3.2/css/bootstrap.min.css"
  = stylesheet_link_tag "//cdn.jsdelivr.net/fontawesome/4.3.0/css/font-awesome.min.css"
  = stylesheet_link_tag "/converse.js-0.9.4/css/converse.min.css"
  :css
    body {
      background-color: transparent;
    }

- content_for :javascript do
  = javascript_include_tag "/converse.js-0.9.4/builds/converse.min.js"
  = javascript_include_tag "//cdn.jsdelivr.net/bootstrap/3.3.2/js/bootstrap.min.js"
  :javascript
    require(['converse'], function (converse) {
      converse.listen.on('ready', function(event) {
        console.log('ready', event)
        converse.rooms.open('#{default_chat_room}@#{CONFERENCE_HOST}');
      });

      converse.listen.on('chatBoxOpened', function (event, chatbox) {
        console.log(event, chatbox)
      });

      converse.listen.on('chatRoomOpened', function (event, chatbox) {
        console.log(event, chatbox)
      });

      converse.listen.on('chatBoxFocused', function (event, chatbox) {
        console.log(event, chatbox)
      });

      converse.listen.on('message', function (event, messageXML) {
        console.log(event, messageXML)
      });

      converse.initialize({
        bosh_service_url: 'https://#{XMPP_HOST}/http-bind/',
        keepalive: true,
        message_carbons: true,
        play_sounds: false,
        roster_groups: false,
        show_controlbox_by_default: false,
        xhr_user_search: false,
        auto_list_rooms: true,
        jid: "#{current_user.jid}",
        prebind_url: "#{prebind_url}",
        authentication: "prebind",
        allow_logout: false,
        allow_contact_requests: false,
        allow_contact_removal: false,
        allow_registration: false,
        animate: false,
        forward_messages: true,
        hide_muc_server: true,
        storage: 'local',
        debug: false
      });
    });

app/views/chat/register.html.haml
.row
  .col-md-4.col-md-offset-4.col-sm-8.col-sm-offset-2.col-xs-12(style="margin-top: 150px")
    - if notice.present?
      .alert.alert-info= notice
    - if alert.present?
      .alert.alert-danger= alert

    .register-container
      %h2 Sign in with
      = link_to user_google_oauth2_omniauth_authorize_path(), class: "btn btn-default btn-lg google btn-block" do
        %i.fa.fa-google.fa-lg
        Google
      = link_to user_facebook_omniauth_authorize_path(), class: "btn btn-default btn-lg facebook btn-block" do
        %i.fa.fa-facebook.fa-lg
        Facebook

- content_for :javascript do
  :javascript
    if (window !== top) {
      top.location.replace('#{root_url}')
    }

app/views/chat/reveal.html.haml
.row
  .col-sm-6
    %h4 User
    %p
      %b Name:
      %span.src-user-name= current_user.xmpp_username
    %p
      %b Password:
      %span.src-user-password= current_user.xmpp_password
    %p
      %b JID:
      %span.src-user-jid= current_user.jid

  .col-sm-6
    %h4 Group chat / Multi-user chat
    %p
      %b Room:
      %span.src-room-name= current_user.rooms.first.name
    %p
      %b Host:
      %span.src-room-host= CONFERENCE_HOST
    %p
      %b JID:
      %span.src-room-jid= current_user.rooms.first.jid